name: Waka Readme Stats

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WakaTime Readme
        uses: KaanEnt/waka-readme-stats@master
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka"
          SHOW_TOTAL_CODE_TIME: 'true'
          SHOW_UPDATED_DATE: 'true'
          UPDATED_DATE_FORMAT: '%d-%m-%Y'
          COMMIT_MESSAGE: "Updated Stats"
          COMMIT_USERNAME: "KaanEnt"
          COMMIT_EMAIL: "unkaanenterprise@gmail.com"
          SHOW_COMMIT: 'false'
          SHOW_PROFILE_VIEWS: 'false'
